// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAmwLDwvRb3bQVHZLRecg2xKbQgw9G8jrQ',
    appId: '1:157738546982:web:c1f4af7b82b065476bf3e7',
    messagingSenderId: '157738546982',
    projectId: 'ecommerce-kit-store',
    authDomain: 'ecommerce-kit-store.firebaseapp.com',
    storageBucket: 'ecommerce-kit-store.appspot.com',
    measurementId: 'G-E774MNP6G3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDF7qIdom5oVfF21JTe7ThYbdqYF4XrNcI',
    appId: '1:157738546982:android:2b3ce21e15add5646bf3e7',
    messagingSenderId: '157738546982',
    projectId: 'ecommerce-kit-store',
    storageBucket: 'ecommerce-kit-store.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC-Y04Dn7XYd7pgVLtwth-qG3n7MksJsSA',
    appId: '1:157738546982:ios:d716c7861837b9ce6bf3e7',
    messagingSenderId: '157738546982',
    projectId: 'ecommerce-kit-store',
    storageBucket: 'ecommerce-kit-store.appspot.com',
    androidClientId: '157738546982-p7n806h4bc252od5ubhnrco120n294ne.apps.googleusercontent.com',
    iosClientId: '157738546982-jh3jnsamrd0icr6jvuk0qlj2s6bco0lf.apps.googleusercontent.com',
    iosBundleId: 'com.example.ecommerceKitStore',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC-Y04Dn7XYd7pgVLtwth-qG3n7MksJsSA',
    appId: '1:157738546982:ios:87f3305cc62787bc6bf3e7',
    messagingSenderId: '157738546982',
    projectId: 'ecommerce-kit-store',
    storageBucket: 'ecommerce-kit-store.appspot.com',
    androidClientId: '157738546982-p7n806h4bc252od5ubhnrco120n294ne.apps.googleusercontent.com',
    iosClientId: '157738546982-qn8p8bds56ntbfv2iolqb24j8h4clmmn.apps.googleusercontent.com',
    iosBundleId: 'com.example.ecommerceKitStore.RunnerTests',
  );
}
